#!/usr/bin/env python
# coding: utf-8

# # Question 1 : Part A

# In[1]:


array = []
for i in range(0, 10):
    for j in range(0, 10):
        for k in range(0, 10):
            array.append(i * j * k)
            
my_array = [i*j*k for i in range(0,10) for j in range(0,10) for k in range(0,10)]

print (my_array)

# # Question 1 : Part B

# In[2]:


assert array == my_array

print (my_array)
